spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "250m"
              memory: 256Mi
            limits:
              cpu: "250m"
              memory: 256Mi
